version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    REPOSITORY_NAME: aws-ci-demo

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
      - IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_NAME:$IMAGE_TAG .

      - docker tag $REPOSITORY_NAME:$IMAGE_TAG $IMAGE_URI

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $IMAGE_URI

      - echo Writing imagedefinitions.json...
      - printf '[{"name":"aws-ci-demo-container","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
